name: Build MyBanYou APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Ambil kode project
        uses: actions/checkout@v3

      - name: Siapkan Java dan Gradle
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Upload hasil APK
        uses: actions/upload-artifact@v4
        with:
          name: MyBanYou-APK
          path: app/build/outputs/apk/debug/*.apk
